"LR": 2e-3
"NUM_ENVS": 16 
"NUM_STEPS": 128 
"TOTAL_TIMESTEPS": 2e7
"FC_DIM_SIZE": 128
"GRU_HIDDEN_DIM": 128
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"SCALE_CLIP_EPS": False
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "tanh"
"ENV_NAME": "MPE_simple_spread_v3"
"SEED": 1
"NUM_SEEDS": 2
"ENV_KWARGS": {}
"ANNEAL_LR": True

# wandb params
"ENTITY": "star-lab-gt"
"PROJECT": "jax-marbler"
"WANDB_MODE": "online"
"WANDB_LOG_ALL_SEEDS": True # will log separately the vmapped seeds

"NUM_TEST_ENVS": 64
"TEST_INTERVAL": 0.05