"LR": 5e-4
"NUM_ENVS": 16
"HIDDEN_SIZE": 512
"TOTAL_TIMESTEPS": 3e6
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 2
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.3
"SCALE_CLIP_EPS": False
"ENT_COEF": 0.01
"VF_COEF": 1.0
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "tanh"
"ANNEAL_LR": True

"NUM_STEPS": 101
# env
"ENV_NAME": "navigation"
"ENV_KWARGS": {
  "num_agents": 3,
  "max_steps": 100,
  "action_type": "Discrete",
  "robotarium": {
    "number_of_robots": 3,
    "show_figure": False,
    "sim_in_real_time": False,
  },
  "controller": {
    "controller": "clf_uni_position",
    "barrier_fn": "robust_barriers",
  },
  "update_frequency": 30
}