# experiment params
"NUM_SEEDS": 1 # number of vmapped seeds
"SEED": 0

"HYP_TUNE": False # perform hyp tune

# wandb params
"ENTITY": "star-lab-gt"
"PROJECT": "jax-marbler"
"WANDB_MODE": "online"
"WANDB_LOG_ALL_SEEDS": False # will log separately the vmapped seeds

# where to save the params (if None, will not save)
"SAVE_PATH": "baselines/QLearning/artifacts"

# visualization
"VISUALIZE": True
"VIS_NUM_ENVS": 5
"VIS_NUM_SEEDS": 1