# ENV
scenario: "Navigation"
"num_agents": 4
"max_steps": 100
"action_type": "Discrete"
"number_of_robots": 4
"controller": "clf_uni_position"
"barrier_fn": "robust_barriers"
"update_frequency": 10
"backend": "python"