"seed": 0
"preprocess_obs": False
"backend": "python"

# ENV
"scenario": "PredatorCapturePrey"
"scenario_file": "predator_capture_prey.py"
"num_agents": 4
"number_of_robots": 4
"num_sensing": 2
"num_capturing": 2
"max_steps": 80
"action_type": "Discrete"
"controller": {
  "controller": "clf_uni_position",
  "barrier_fn": "robust_barriers" 
}
heterogeneity: {
  "type": "capability_set",
  "obs_type": "full_capability_set",
  "values": [[0.45, 0], [0.45, 0], [0, 0.25], [0, 0.25]],
  "sample": False,
}
"update_frequency": 30
"initial_conditions": [[-0.41666667,  0.15      , -1.4118529 ],
       [-0.11666667,  0.45      , -0.60490503],
       [-0.11666667, -0.45      ,  2.3417095 ],
       [ 0.18333333, -0.75      ,  2.85722991],
       [-0.25      , -0.75      , -0.78313699],
       [-0.25      ,  0.25      , -2.14020053],
       [ 0.25      , -0.75      , -1.70690304],
       [ 0.25      ,  0.25      , -2.03460976],
       [ 1.25      , -0.75      ,  1.09819411],
       [-0.75      , -0.25      ,  2.22400703]]

# MODEL CONFIG
"input_dim": 38
"hidden_dim": 512
"output_dim": 5

# DEPLOYMENT CONFIG
"model_weights": "qmix_rnn_predator_capture_prey_seed0_vmap1.safetensors"
"model_file": "actor.py"
"model_class": RNNActor
"save_gif": True